# Generated by Django 4.2 on 2023-04-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
