# Generated by Django 4.2 on 2023-04-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxTest', '0003_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='user does not provied bio', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_handle',
            field=models.CharField(blank=True, default='no facebook', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, default='no instagram', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, default='no twitter', max_length=50),
        ),
    ]
