# Generated by Django 4.2 on 2023-04-25 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxTest', '0005_myuser_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajaxTest.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/images/default_user.png', upload_to='profile_pics/'),
        ),
    ]
