# Generated by Django 4.2 on 2023-04-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxTest', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='sample_ajax/ajaxTest/static/images/default_user.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='sample_ajax/ajaxTest/static/images/default_user.jpg', upload_to='profile_pics/'),
        ),
    ]
