# Generated by Django 4.2 on 2023-04-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxTest', '0009_alter_post_image_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
